"""Fresh German frame bank for the S2 synthetic generator."""

GENERAL_PERSON = (
    "{name} prüfte den erfundenen Freigabevorgang vor der wöchentlichen Auswertung.",
    "Der Service Desk leitete das synthetische Prüfungspaket an {name} weiter.",
    "Vor dem Abschluss bestätigte {name} die fiktive Änderungszusammenfassung.",
    "Die Testkoordination bat {name}, den erfundenen Ablaufnachweis zu prüfen.",
    "Für die Übung dokumentierte {name} die synthetische Eskalationsentscheidung.",
    "{name} bestätigte die fiktive Migrationscheckliste für den nächsten Testschritt.",
    "Eine interne Demo ordnete {name} die simulierte Zugriffsanfrage zu.",
    "Das Übungsaudit vermerkte {name} als prüfende Person im erfundenen Kontrollhinweis.",
    "Während des Probelaufs genehmigte {name} den synthetischen Übergangsplan.",
    "Die fiktive Störungsübung bat {name} um eine abschließende Statusmeldung.",
    "{name} verglich den Musterfreigabedatensatz mit dem geplanten Wartungsfenster.",
    "Ein Trainingsablauf sandte {name} die simulierte Ausnahme zur Bestätigung.",
    "Die Sandbox-Koordination notierte, dass {name} die erfundene Prüfung erledigte.",
    "Für einen Beispielbericht prüfte {name} das synthetische Nachweispaket.",
    "Die Demonstrationswarteschlange legte die fiktive Anfrage bei {name} ab.",
    "{name} gab im Testtermin Rückmeldung zum erfundenen Änderungsvorschlag.",
    "Das Übungsprotokoll sagt, dass {name} die simulierte Checkliste prüfte.",
    "Ein synthetischer Freigabezyklus bat {name}, die Testübergabe zu bewerten.",
    "Der Trainingsfall nennt {name} als prüfende Person für einen erfundenen Supportvorgang.",
    "Vor Ende der Übung zeichnete {name} den simulierten Maßnahmenhinweis ab.",
)

GENERAL_CLEAN = (
    "Der erfundene Freigabevorgang ist vor der wöchentlichen Auswertung geprüft.",
    "Der Service Desk leitete das synthetische Prüfungspaket an die Warteschlange weiter.",
    "Vor dem Abschluss wurde die fiktive Änderungszusammenfassung bestätigt.",
    "Die Testkoordination prüfte den erfundenen Ablaufnachweis für die Übung.",
    "Für die Übung wurde die synthetische Eskalationsentscheidung dokumentiert.",
    "Die fiktive Migrationscheckliste ist für den nächsten Testschritt bereit.",
    "Eine interne Demo prüfte die simulierte Zugriffsanfrage in der Trainingswarteschlange.",
    "Das Übungsaudit vermerkte den erfundenen Kontrollhinweis zur späteren Prüfung.",
    "Während des Probelaufs wurde der synthetische Übergangsplan genehmigt.",
    "Die fiktive Störungsübung erzeugte eine abschließende Statusmeldung.",
    "Der Musterfreigabedatensatz wurde mit dem geplanten Wartungsfenster verglichen.",
    "Ein Trainingsablauf sandte die simulierte Ausnahme zur Bestätigung.",
    "Die Sandbox-Koordination erledigte die erfundene Prüfung im Testsystem.",
    "Für einen Beispielbericht wurde das synthetische Nachweispaket geprüft.",
    "Die Demonstrationswarteschlange hielt die fiktive Anfrage zur Prüfung bereit.",
    "Der erfundene Änderungsvorschlag erhielt im Testtermin Rückmeldung.",
    "Das Übungsprotokoll bestätigte die simulierte Checkliste.",
    "Ein synthetischer Freigabezyklus bewertete die Testübergabe.",
    "Der Trainingsfall enthält einen erfundenen Supportvorgang zur Prüfung.",
    "Vor Ende der Übung wurde der simulierte Maßnahmenhinweis abgezeichnet.",
)

# The exact surface is capitalized in the vocabulary.  Each word is therefore
# rendered in a compatible sentence position rather than forced through a
# generic conjunction slot (delta audit D2 class B).
FUNCTION_KEEP = {
    "Weil": (
        "{surface} die synthetische Prüfung noch läuft, bleibt der Vorgang offen.",
        "{surface} die Demo noch vorbereitet wird, wartet die Trainingswarteschlange.",
        "{surface} der Probelauf andauert, bleibt die fiktive Anfrage sichtbar.",
        "{surface} die Kontrollprüfung nicht endet, wird nichts abgeschlossen.",
        "{surface} die automatische Eskalation im ITSM-Workflow erst nach dem Abgleich der Abhängigkeitsdaten freigegeben werden darf, dokumentiert das Service-Team den Zwischenstand im Change-Protokoll.",
        "{surface} im geplanten Wartungsfenster noch ein Rückruf der Fachgruppe aussteht, verschiebt die Sachbearbeitung die endgültige Zuweisung in die nächste Bearbeitungsrunde.",
        "{surface} die Schnittstelle zum Testmandanten während der Validierung keine bestätigte Antwort liefert, bleibt die Freigabe mit einer nachvollziehbaren Begründung gesperrt.",
        "{surface} die Beweisakte für den simulierten Störungsfall vor der Übergabe vollständig geprüft werden muss, eröffnet die Koordination keinen Abschlussstatus.",
    ),
    "Falls": (
        "{surface} die synthetische Prüfung länger dauert, bleibt der Vorgang offen.",
        "{surface} die Demo verschoben wird, wartet die Trainingswarteschlange.",
        "{surface} der Probelauf noch läuft, bleibt die fiktive Anfrage sichtbar.",
        "{surface} die Kontrollprüfung fehlschlägt, wird der Test erneut gestartet.",
        "{surface} die Genehmigungsregel im Servicekatalog eine zusätzliche Kontrolle verlangt, legt das ITSM-Team einen begründeten Nachtrag zum Änderungsauftrag an.",
        "{surface} der Abgleich mit dem Testsystem eine abweichende Versionsnummer meldet, wartet die Freigabestelle auf den protokollierten Korrekturlauf.",
        "{surface} sich im simulierten Incident neue Abhängigkeiten zeigen, verteilt die Einsatzleitung die offenen Prüfpunkte an die zuständigen Fachgruppen.",
        "{surface} die dokumentierte Rückfalloption aktiviert werden muss, informiert die Koordination den Übungskreis vor dem nächsten technischen Schritt.",
    ),
    "Wegen": (
        "{surface} der synthetischen Prüfung bleibt der Vorgang für die Übung offen.",
        "{surface} des geplanten Probelaufs wartet die Trainingswarteschlange.",
        "{surface} einer fiktiven Freigabe bleibt die Anfrage im Prüfstatus.",
        "{surface} des simulierten Fehlers wird der Test später fortgesetzt.",
        "{surface} des noch nicht signierten Change-Protokolls bleibt die technische Übergabe im Übungsregister als wartend vermerkt.",
        "{surface} der fehlenden Rückmeldung aus der Testumgebung erstellt das Service-Team zunächst keinen verbindlichen Abschlussvermerk.",
        "{surface} eines unerwarteten Abgleichfehlers im fiktiven Identitätsdienst plant die Koordination einen zusätzlichen, nachvollziehbaren Prüfschritt.",
        "{surface} des vorgesehenen Wartungsfensters führt die Fachgruppe die Simulation erst nach der dokumentierten Freigabe weiter.",
    ),
    "Ebene": (
        "Auf dieser {surface} bleibt die Übung für die weitere Prüfung offen.",
        "Die technische {surface} trennt den Testablauf von der Produktionsumgebung.",
        "Auf der nächsten {surface} prüft das Team den synthetischen Nachweis.",
        "Diese {surface} der Simulation enthält nur erfundene Kontrollschritte.",
        "Auf der administrativen {surface} ordnet das ITSM-Team die Rückmeldung dem simulierten Änderungsauftrag zu, bevor die technische Prüfung beginnt.",
        "Die fachliche {surface} der Übung beschreibt, welche Nachweise vor einer erfundenen Freigabe von der zuständigen Rolle bestätigt werden müssen.",
        "Zwischen der technischen {surface} des Testmandanten und dem Schulungsablauf liegt eine dokumentierte Kontrollschicht für die fiktive Übergabe.",
        "Auf welcher {surface} eine Abweichung bewertet wird, hält das Service-Protokoll mit einem begründeten Verweis auf den Übungsfall fest.",
    ),
    "Einen": (
        "{surface} Moment wartet die Testkoordination vor dem nächsten Prüfschritt.",
        "{surface} weiteren Testlauf startet das Team nach der Freigabe.",
        "{surface} kurzen Abgleich führt die Übungsgruppe vor dem Abschluss durch.",
        "{surface} zusätzlichen Kontrollschritt dokumentiert der Trainingsablauf heute.",
        "{surface} vollständigen Auszug aus dem simulierten Änderungsprotokoll prüft die Service-Koordination, bevor sie die nächste Übungsphase freigibt.",
        "{surface} abgestimmten Rückfallplan legt das ITSM-Team dem Trainingskreis zusammen mit den dokumentierten Abhängigkeiten zur Bestätigung vor.",
        "{surface} kurzen Hinweis zur fehlenden Testantwort nimmt die Fachgruppe in den nachvollziehbaren Statusbericht für die Übung auf.",
        "{surface} prüfbaren Nachweis über den fiktiven Freigabeschritt fordert die Koordination vor dem Abschluss des simulierten Incidents an.",
    ),
}

FUNCTION_REDACT = (
    "Herr {surface} bestätigte den fiktiven Vorgang im Testsystem vor dem Abschluss.",
    "Frau {surface} prüfte die synthetische Freigabe während der Trainingsübung.",
    "Im Probelauf dokumentierte Herr {surface} die erfundene Änderungsentscheidung.",
    "Die Testkoordination bat Frau {surface} um Rückmeldung zum Musterablauf.",
    "Herr {surface} bestätigte die simulierte Checkliste für die Demo.",
    "Für die Übung prüfte Frau {surface} den fiktiven Nachweis im Register.",
    "Der Trainingsfall wurde von Herrn {surface} vor dem Abschluss bewertet.",
    "Frau {surface} leitete die synthetische Anfrage an die Prüfwarteschlange weiter.",
    "Im Testbericht bestätigte Herr {surface} die erfundene Statusmeldung.",
    "Die Sandbox notierte, dass Frau {surface} den Musterfall überprüfte.",
    "Herr {surface} gab Rückmeldung zur simulierten Freigabe im Übungstermin.",
    "Vor dem Probelauf prüfte Frau {surface} den fiktiven Kontrollhinweis.",
    "Das Übungsprotokoll nennt Herrn {surface} als prüfende Person.",
    "Frau {surface} zeichnete den synthetischen Maßnahmenhinweis im Testsystem ab.",
    "Für den Beispielbericht bestätigte Herr {surface} die Demoübergabe.",
    "Die Trainingskoordination ordnete Frau {surface} die Musterprüfung zu.",
    "Herr {surface} bewertete die fiktive Ausnahme im simulierten Ablauf und hinterlegte seine nachvollziehbare Entscheidung im Übungsprotokoll des Service-Teams.",
    "Vor Ende der Übung bestätigte Frau {surface} den Teststatus, nachdem sie die dokumentierten Abhängigkeiten mit der Trainingskoordination abgeglichen hatte.",
    "Nach dem technischen Abgleich erhielt der Probelauf eine begründete Rückmeldung von Herrn {surface}, die im fiktiven Change-Register gespeichert wurde.",
    "Im abschließenden ITSM-Review schloss Frau {surface} die erfundene Prüfung erst ab, nachdem der simulierte Nachweis vollständig vorlag.",
)

# (zone, REDACT frame, KEEP frame), with the same safety properties as the
# English bank and German-native labels surrounding the ambiguous identifier.
STRUCTURAL_FRAMES = (
    ("code_identifier", "// synthetische Prüfzuordnung\nlet verantwortung = {surface};\nreturn trainingsWarteschlange.pruefen(verantwortung, regelwerk);", "// synthetische Regelzuordnung\nlet regelSchluessel = {surface};\nreturn trainingsWarteschlange.pruefen(regelSchluessel, regelwerk);"),
    ("code_identifier", "function bereiteUebungVor() {{\n  const ansprechperson = {surface};\n  return demoPruefung.senden(ansprechperson, nachweis);\n}}", "function bereiteUebungVor() {{\n  const konfiguration = {surface};\n  return demoPruefung.senden(konfiguration, nachweis);\n}}"),
    ("technical_id", "protokoll person={surface} ereignis=synthetische_pruefung status=wartend regel=training", "protokoll schluessel={surface} ereignis=synthetische_pruefung status=wartend regel=training"),
    ("json_value", "{{\"angefordert_fuer\":\"{surface}\",\"vorgang\":\"{ticket}\",\"ablauf\":\"synthetische_pruefung\",\"status\":\"wartend\"}}", "{{\"konfigurationsschluessel\":\"{surface}\",\"vorgang\":\"{ticket}\",\"ablauf\":\"synthetische_pruefung\",\"status\":\"wartend\"}}"),
    ("code_identifier", "// Demo-Freigabekontext\nlet pruefperson = {surface};\nlet ergebnis = bewerteMuster(pruefperson, kontrollen);\nreturn ergebnis;", "// Demo-Konfigurationskontext\nlet pruefregel = {surface};\nlet ergebnis = bewerteMuster(pruefregel, kontrollen);\nreturn ergebnis;"),
    ("technical_id", "ereignis=demo_uebergabe angefordert_von={surface} warteschlange=training status=wartend nachweis=synthetisch", "ereignis=demo_uebergabe konfigurationswert={surface} warteschlange=training status=wartend nachweis=synthetisch"),
    ("json_value", "{{\"freigabekontakt\":\"{surface}\",\"aenderung\":\"{ticket}\",\"umgebung\":\"sandbox\",\"geprueft\":false}}", "{{\"regelkennung\":\"{surface}\",\"aenderung\":\"{ticket}\",\"umgebung\":\"sandbox\",\"geprueft\":false}}"),
    ("code_identifier", "class SynthetischePruefung {{\n  constructor() {{ this.person = {surface}; }}\n  senden() {{ return this.person + pruefkontext; }}\n}}", "class SynthetischePruefung {{\n  constructor() {{ this.einstellung = {surface}; }}\n  senden() {{ return this.einstellung + pruefkontext; }}\n}}"),
    ("technical_id", "protokoll=uebungsaudit person={surface} aktion=musterfall_pruefen ergebnis=offen", "protokoll=uebungsaudit kennung={surface} aktion=musterfall_pruefen ergebnis=offen"),
    ("json_value", "{{\"pruefperson\":\"{surface}\",\"referenz\":\"{ticket}\",\"quelle\":\"training\",\"aufbewahren\":false}}", "{{\"techniktoken\":\"{surface}\",\"referenz\":\"{ticket}\",\"quelle\":\"training\",\"aufbewahren\":false}}"),
    ("code_identifier", "// erfundenes Freigabegitter\nconst menschlichePerson = {surface};\nconst meldung = baueUebungshinweis(menschlichePerson, wartungsfenster);", "// erfundenes Freigabegitter\nconst konfigurationswert = {surface};\nconst meldung = baueUebungshinweis(konfigurationswert, wartungsfenster);"),
    ("technical_id", "dienst=beispielportal vertretung={surface} ereignis=muster_aenderung status=geplant spur=synthetisch", "dienst=beispielportal option={surface} ereignis=muster_aenderung status=geplant spur=synthetisch"),
    ("json_value", "{{\"zugeordnete_person\":\"{surface}\",\"fall\":\"{ticket}\",\"phase\":\"uebung\",\"ergebnis\":\"offen\"}}", "{{\"zugeordnete_einstellung\":\"{surface}\",\"fall\":\"{ticket}\",\"phase\":\"uebung\",\"ergebnis\":\"offen\"}}"),
    ("code_identifier", "async function starteDemo() {{\n  const kontakt = {surface};\n  return await synthetischePruefung(kontakt, nachweispaket);\n}}", "async function starteDemo() {{\n  const token = {surface};\n  return await synthetischePruefung(token, nachweispaket);\n}}"),
    ("technical_id", "datensatz=trainingsfall pruefer={surface} aktion=erfundene_freigabe ergebnis=protokolliert", "datensatz=trainingsfall schluessel={surface} aktion=erfundene_freigabe ergebnis=protokolliert"),
    ("json_value", "{{\"personenreferenz\":\"{surface}\",\"lauf\":\"{ticket}\",\"art\":\"demo\",\"vollstaendig\":true}}", "{{\"konfigurationsreferenz\":\"{surface}\",\"lauf\":\"{ticket}\",\"art\":\"demo\",\"vollstaendig\":true}}"),
    ("code_identifier", "// nur interne Übung\nvar freigabePerson = {surface};\nvar status = verarbeiteMusterfreigabe(freigabePerson, beispielregel);", "// nur interne Übung\nvar auswahlToken = {surface};\nvar status = verarbeiteMusterfreigabe(auswahlToken, beispielregel);"),
    ("technical_id", "audit=musterablauf kontakt={surface} phase=pruefung warteschlange=simulation entscheidung=wartend", "audit=musterablauf konfiguration={surface} phase=pruefung warteschlange=simulation entscheidung=wartend"),
    ("json_value", "{{\"vertretungsname\":\"{surface}\",\"anfrage\":\"{ticket}\",\"kanal\":\"test\",\"hinweis\":\"synthetisch\"}}", "{{\"vertretungsschluessel\":\"{surface}\",\"anfrage\":\"{ticket}\",\"kanal\":\"test\",\"hinweis\":\"synthetisch\"}}"),
    ("code_identifier", "function pruefeUebung() {{\n  const benanntePerson = {surface};\n  return fasseSynthetischZusammen(benanntePerson, auditspur);\n}}", "function pruefeUebung() {{\n  const benannteEinstellung = {surface};\n  return fasseSynthetischZusammen(benannteEinstellung, auditspur);\n}}"),
)

STRUCTURAL_CONTEXTS = (
    ("Die Trainingsprüfung bewertet eine erfundene Zuordnung vor der Ausführung.", "Der Nachweis bleibt innerhalb der isolierten Demonstrationsumgebung."),
    ("Die Übungskoordination prüft diese simulierte Zuweisung sorgfältig.", "An dieser Übung ist keine reale Identität beteiligt."),
    ("Ein Sandbox-Ablauf protokolliert hier einen synthetischen Freigabekontext.", "Der Trainingsfall endet nach der erfundenen Bestätigung."),
    ("Diese Demo-Nachricht unterstützt eine fiktive Serviceübergabe.", "Prüfende verwenden sie nur während der Trainingssitzung."),
    ("Musterkontrollen dokumentieren heute eine nichtproduktive Zugriffsentscheidung.", "Das Nachweispaket bleibt im Übungsumfang gespeichert."),
    ("Das Muster-Audit verfolgt eine erfundene betriebliche Änderung.", "Sein Ergebnis dient ausschließlich der Demonstration."),
    ("Eine Trainingswarteschlange bereitet den simulierten Prüfpunkt vor.", "Die Testkoordination bestätigt später das erfundene Ergebnis."),
    ("Diese interne Übung validiert einen erfundenen Ablaufsschritt.", "Alle Begleitdaten beschreiben die Sandbox-Umgebung."),
    ("Der Übungsdatensatz hält einen synthetischen Kontrollpunkt fest.", "Hier erscheinen keine Live-Konten oder Kundendaten."),
    ("Ein Probelauf leitet die fiktive Anfrage sicher weiter.", "Der Musternachweis wird vor dem Abschluss geprüft."),
    ("Trainingsverantwortliche prüfen gemeinsam diese simulierte Freigabeentscheidung.", "Das Szenario bleibt auf nichtproduktive Systeme beschränkt."),
    ("Das Demonstrationsprotokoll erläutert einen erfundenen Übergabestatus.", "Eine spätere Übungsprüfung erfasst das simulierte Ergebnis."),
    ("Diese Musteraufgabe bildet einen fiktiven Freigabepfad ab.", "Das Übungsteam validiert nur synthetische Nachweise."),
    ("Ein Sandbox-Fall verfolgt die erfundene Prüfverantwortung.", "Sein Musterstatus bleibt während des Probelaufs sichtbar."),
    ("Der Testablauf dokumentiert sorgfältig eine simulierte Ausnahme.", "Trainingspersonal bestätigt anschließend die erfundene Reaktion."),
    ("Ein Übungsregister speichert dieses künstliche Kontrollereignis.", "Die Demonstrationsgrenze verhindert jede reale Verwendung."),
    ("Diese Probenachricht unterstützt eine fiktive Änderungsprüfung.", "Der synthetische Fall wird nach dem Testlauf verworfen."),
    ("Die interne Demo folgt einer erfundenen Freigabereihenfolge.", "Nur die Trainingswarteschlange erhält dieses Musterartefakt."),
    ("Ein Musterprozess erfasst eine künstliche Routingentscheidung.", "Der Übungsnachweis bleibt von Live-Systemen getrennt."),
    ("Dieses synthetische Szenario testet einen fiktiven Prüffluss.", "Das Übungsaudit vermerkt den simulierten Abschlussstatus."),
)
