"""Fresh English frame bank for the S2 synthetic generator.

All frames are authored locally.  The paired hard and structural templates
deliberately reuse ``{surface}`` in opposing contexts.
"""

GENERAL_PERSON = (
    "{name} requested confirmation for the synthetic access record before the weekly review.",
    "The service desk routed the fictional approval package to {name} for verification.",
    "Before closure, {name} reviewed the synthetic change summary with the release team.",
    "The test coordinator asked {name} to validate the invented workflow evidence.",
    "For the rehearsal, {name} documented the synthetic escalation decision in the register.",
    "{name} confirmed that the fictional migration checklist was ready for the next stage.",
    "An internal demo assigned {name} to inspect the simulated access request.",
    "The practice audit recorded {name} as reviewer of the fabricated control note.",
    "During the dry run, {name} approved the synthetic service transition plan.",
    "The fictional incident exercise asked {name} for a final status update.",
    "{name} compared the mock approval record with the planned release window.",
    "A training workflow sent {name} the simulated exception for acknowledgement.",
    "The sandbox coordinator noted that {name} completed the invented review task.",
    "For a sample report, {name} checked the synthetic evidence bundle before publication.",
    "The demonstration queue placed the fictional access request with {name}.",
    "{name} supplied feedback on the mock change proposal during the test meeting.",
    "The rehearsal log says {name} verified the fabricated deployment checklist.",
    "A synthetic approval cycle asked {name} to assess the test-system handoff.",
    "The training case lists {name} as the reviewer for an invented support record.",
    "Before the exercise ended, {name} signed off on the simulated remediation note.",
)

GENERAL_CLEAN = (
    "The synthetic access record is ready for the weekly review and confirmation.",
    "The service desk routed the fictional approval package to the verification queue.",
    "Before closure, the synthetic change summary was reviewed with the release team.",
    "The test coordinator validated the invented workflow evidence for the rehearsal.",
    "For the rehearsal, the synthetic escalation decision was documented in the register.",
    "The fictional migration checklist was ready for the next stage of validation.",
    "An internal demo inspected the simulated access request in the training queue.",
    "The practice audit recorded the fabricated control note for later review.",
    "During the dry run, the synthetic service transition plan received approval.",
    "The fictional incident exercise produced a final status update for the team.",
    "The mock approval record was compared with the planned release window.",
    "A training workflow sent the simulated exception for acknowledgement.",
    "The sandbox coordinator completed the invented review task in the test system.",
    "For a sample report, the synthetic evidence bundle was checked before publication.",
    "The demonstration queue held the fictional access request for review.",
    "The mock change proposal received feedback during the test meeting.",
    "The rehearsal log verified the fabricated deployment checklist.",
    "A synthetic approval cycle assessed the test-system handoff.",
    "The training case contains an invented support record for the reviewer.",
    "Before the exercise ended, the simulated remediation note received sign-off.",
)

VENDOR_KEEP = (
    "{{\"provider\":\"{surface}\",\"connection_state\":\"ready\",\"environment\":\"synthetic\"}}",
    "The synthetic integration catalog marks {surface} as an approved provider for testing.",
    "provider_name={surface} lifecycle=demo state=ready review=scheduled",
    "{{\"vendor\":\"{surface}\",\"purpose\":\"fictional_onboarding\",\"status\":\"queued\"}}",
    "The sandbox contract register lists {surface} under the synthetic vendor review.",
    "integration.provider = \"{surface}\"; integration.mode = \"test\";",
    "A mock procurement record identifies {surface} as the provider for this exercise.",
    "vendor={surface} ticket=DEMO-approval scope=training-only result=ready",
    "The fictional service inventory stores {surface} in its vendor reference field.",
    "{{\"external_provider\":\"{surface}\",\"review_cycle\":\"sample\",\"enabled\":true}}",
    "For the rehearsal, {surface} remains a vendor label in the synthetic dependency map.",
    "The test environment associates {surface} with a non-production connector.",
    "provider: {surface}; classification: vendor; usage: simulated_validation",
    "The mock change record names {surface} as a third-party service provider.",
    "{{\"supplier\":\"{surface}\",\"assessment\":\"synthetic\",\"owner_queue\":\"review\"}}",
    "The fictional onboarding checklist refers to {surface} only as a vendor system.",
    "catalog_entry provider={surface} source=demo verification=pending",
    "The sample architecture note classifies {surface} as an external vendor dependency.",
    "integrationConfig.provider = \"{surface}\"; integrationConfig.synthetic = true;",
    "A training asset keeps {surface} in the vendor column of the simulated register.",
)

VENDOR_PERSON = (
    "{surface} approved a fictional vendor onboarding note during the exercise.",
    "The training coordinator asked {surface} to review the mock provider request.",
    "For the rehearsal, {surface} documented the simulated supplier decision.",
    "{surface} confirmed the invented onboarding checklist before its test review.",
    "A fictional procurement task assigned {surface} to validate the sample record.",
    "The practice audit recorded {surface} as reviewer of the mock connector request.",
    "During the dry run, {surface} supplied feedback on the simulated vendor form.",
    "The test workflow routed the fabricated approval item to {surface}.",
    "{surface} checked the synthetic contract note before the training session closed.",
    "An internal demo lists {surface} as the contact for the invented provider case.",
    "The rehearsal log says {surface} verified the fictional dependency request.",
    "For a sample exercise, {surface} accepted the mock onboarding handoff.",
    "The test coordinator recorded a synthetic status update from {surface}.",
    "{surface} reviewed the fabricated service assessment with the practice team.",
    "A demonstration queue assigned the fictional supplier note to {surface}.",
    "Before closure, {surface} confirmed the simulated connector review.",
    "The invented procurement case asked {surface} for an acknowledgement.",
    "{surface} completed the training review of the mock service request.",
    "The sandbox report names {surface} as reviewer of the fictional vendor item.",
    "During the exercise, {surface} signed off on the simulated onboarding evidence.",
)

REGION_KEEP = (
    "Deployment target {surface} remains within the synthetic rollout plan and test boundary.",
    "The demo environment records {surface} as the cloud region for a fictional service.",
    "region={surface} workload=training-api stage=simulation status=ready",
    "{{\"cloud_region\":\"{surface}\",\"deployment\":\"synthetic\",\"approved\":true}}",
    "The sample architecture map keeps {surface} as an infrastructure region label.",
    "deployment.region = \"{surface}\"; deployment.mode = \"rehearsal\";",
    "A mock release plan targets {surface} for the non-production rollout.",
    "The fictional platform inventory classifies {surface} as a cloud location code.",
    "region: {surface}; policy: training-only; backup: disabled",
    "The sandbox configuration stores {surface} in its regional routing setting.",
    "{{\"target_region\":\"{surface}\",\"change_ref\":\"demo\",\"state\":\"queued\"}}",
    "For the exercise, {surface} remains a technical region value in the plan.",
    "The test deployment notes {surface} as the selected infrastructure geography.",
    "The simulated routing rule points the mock workload to {surface}.",
    "cloud.region={surface} audit=synthetic retention=none",
    "A training document names {surface} only as a platform region identifier.",
    "The fictional release checklist retains {surface} in the cloud target field.",
    "environment.region = \"{surface}\"; environment.demo = true;",
    "The rehearsal inventory lists {surface} beside the simulated compute service.",
    "A mock operations record treats {surface} as an infrastructure routing token.",
)

REGION_PERSON = (
    "{surface} updated the fictional rollout note before the rehearsal review.",
    "The training coordinator asked {surface} to verify the simulated deployment plan.",
    "For the mock release, {surface} documented the invented service transition.",
    "{surface} confirmed the test-system routing decision during the exercise.",
    "A fictional change task assigned {surface} to inspect the sample rollout evidence.",
    "The practice audit recorded {surface} as reviewer of the synthetic region request.",
    "During the dry run, {surface} approved the fabricated deployment checklist.",
    "The rehearsal workflow sent the simulated release note to {surface}.",
    "{surface} checked the mock infrastructure plan before its training handoff.",
    "An internal demo lists {surface} as contact for the fictional rollout case.",
    "The test log says {surface} acknowledged the simulated routing update.",
    "For a sample exercise, {surface} reviewed the invented environment record.",
    "The training coordinator recorded feedback from {surface} on the mock release.",
    "{surface} validated the fictional change window with the practice team.",
    "A demonstration queue placed the simulated rollout approval with {surface}.",
    "Before closure, {surface} confirmed the synthetic deployment review.",
    "The invented operations case asked {surface} for a status update.",
    "{surface} completed the rehearsal check for the mock routing task.",
    "The sandbox report names {surface} as reviewer of the fictional region item.",
    "During the exercise, {surface} signed off on the simulated rollout evidence.",
)

ROLE_KEEP = (
    "The {surface} completed the synthetic access review for the training record.",
    "In the rehearsal, the {surface} routed the fictional approval to the test queue.",
    "The sample workflow assigns the {surface} a non-production review task.",
    "For the demo, the {surface} verifies the invented change evidence.",
    "The simulated service catalog lists the {surface} as a functional role.",
    "A training checklist asks the {surface} to inspect the mock request.",
    "The practice audit records the {surface} as a group role, not a person.",
    "During the dry run, the {surface} approves the fabricated control note.",
    "The fictional handoff directs the {surface} to the sandbox review queue.",
    "A test process uses the {surface} as a shared operational responsibility.",
    "The rehearsal guide identifies the {surface} as a role in the sample flow.",
    "For this exercise, the {surface} receives the synthetic access item.",
    "The mock transition plan gives the {surface} a team-based review step.",
    "The training record stores the {surface} as an organizational function.",
    "A fictional workflow expects the {surface} to complete the test check.",
    "The sandbox ticket routes the simulated evidence to the {surface} role.",
    "The practice coordinator treats the {surface} as a shared service function.",
    "In the demo register, the {surface} is an operational title only.",
    "The synthetic approval plan assigns the {surface} to its review stage.",
    "A mock audit references the {surface} as a role phrase in the process.",
)

ROLE_PERSON = (
    "{surface} completed the fictional access review for the training record.",
    "In the rehearsal, {surface} routed the synthetic approval to the test queue.",
    "The sample workflow assigned {surface} a non-production review task.",
    "For the demo, {surface} verified the invented change evidence.",
    "The simulated service catalog lists {surface} as the contact for the exercise.",
    "A training checklist asked {surface} to inspect the mock request.",
    "The practice audit recorded {surface} as reviewer of the fictional group note.",
    "During the dry run, {surface} approved the fabricated control note.",
    "The fictional handoff directed {surface} to the sandbox review queue.",
    "A test process asked {surface} to confirm the operational responsibility.",
    "The rehearsal guide identifies {surface} as reviewer in the sample flow.",
    "For this exercise, {surface} received the synthetic access item.",
    "The mock transition plan gave {surface} a review step for the practice team.",
    "The training record stores feedback supplied by {surface} during rehearsal.",
    "A fictional workflow expected {surface} to complete the test check.",
    "The sandbox ticket routed the simulated evidence to {surface}.",
    "The practice coordinator asked {surface} to confirm the service function.",
    "In the demo register, {surface} appears as the reviewer for this case.",
    "The synthetic approval plan assigned {surface} to its review stage.",
    "A mock audit names {surface} as the person who checked the process.",
)

LOCATION_KEEP = tuple(
    (
        "schema_label: {surface}; value_type: synthetic_reference; review_state: ready",
        "The sample schema registers {surface} as a fictional location label for testing.",
        "field=location_label value={surface} source=demo classification=reference",
        "{{\"schema_location\":\"{surface}\",\"dataset\":\"synthetic\",\"state\":\"ready\"}}",
        "The mock configuration retains {surface} as a schema-facing place token.",
        "schema.locationLabel = \"{surface}\"; schema.synthetic = true;",
        "A training definition uses {surface} as a non-personal reference location.",
        "label={surface} namespace=sample-schema validation=complete",
        "The fictional data model stores {surface} in its location-label field.",
        "{{\"reference_place\":\"{surface}\",\"purpose\":\"demo\",\"active\":true}}",
        "For the exercise, {surface} remains a schema label rather than a travel record.",
        "The sandbox dictionary maps {surface} to a synthetic place reference.",
        "location_label: {surface}; allowed_value: true; origin: rehearsal",
        "The mock metadata classifies {surface} as a test-only location label.",
        "{{\"label\":\"{surface}\",\"field_type\":\"reference\",\"scope\":\"training\"}}",
        "The fictional schema checklist includes {surface} in the allowed label set.",
        "schema_entry label={surface} use=synthetic validation=pending",
        "The sample model treats {surface} as a static reference-place value.",
        "config.location_label = \"{surface}\"; config.demo = true;",
        "A rehearsal asset stores {surface} as a schema token for test data.",
    )
)

VENDOR_KEEP_ZONES = (
    "json_value", "prose", "technical_id", "json_value", "prose", "code_identifier", "prose", "technical_id", "prose", "json_value",
    "prose", "prose", "technical_id", "prose", "json_value", "prose", "technical_id", "prose", "code_identifier", "prose",
)

REGION_KEEP_ZONES = (
    "prose", "prose", "technical_id", "json_value", "prose", "code_identifier", "prose", "prose", "technical_id", "prose",
    "json_value", "prose", "prose", "prose", "technical_id", "prose", "prose", "code_identifier", "prose", "prose",
)

LOCATION_KEEP_ZONES = (
    "schema_label", "prose", "schema_label", "json_value", "prose", "code_identifier", "prose", "schema_label", "prose", "json_value",
    "prose", "prose", "schema_label", "prose", "json_value", "prose", "schema_label", "prose", "code_identifier", "prose",
)

LOCATION_REDACT = (
    ("LOCATION", "The fictional itinerary lists a stop in {surface} before the workshop begins."),
    ("LOCATION", "The mock travel record places the training meeting in {surface} on Tuesday."),
    ("LOCATION", "A simulated route from {surface} to the demo venue received approval."),
    ("LOCATION", "The reimbursement exercise records an overnight stay in {surface}."),
    ("LOCATION", "The practice itinerary marks {surface} as the departure location."),
    ("LOCATION", "A fictional booking note gives {surface} as the destination for the training visit."),
    ("LOCATION", "The demo travel request schedules a transfer through {surface}."),
    ("LOCATION", "The test route identifies {surface} as the location of the sample meeting."),
    ("LOCATION", "The synthetic expense form refers to travel from {surface}."),
    ("LOCATION", "A rehearsal calendar records a workshop in {surface}."),
    ("PERSON", "{surface}, the assigned reviewer, approved the fictional travel request."),
    ("PERSON", "Mr. {surface} confirmed the simulated itinerary during the training exercise."),
    ("PERSON", "The training coordinator asked Ms. {surface} to review the mock travel request."),
    ("PERSON", "Our colleague {surface} updated the invented travel exception before the review."),
    ("PERSON", "Employee {surface} checked the fictional route plan before the handoff."),
    ("PERSON", "The travel case lists {surface} as the reviewer for the simulated approval."),
    ("PERSON", "A note from {surface} confirmed the sample journey details for the exercise."),
    ("PERSON", "The practice audit recorded feedback from {surface} on the mock trip."),
    ("PERSON", "The test workflow assigned the itinerary question to reviewer {surface}."),
    ("PERSON", "The HR-style exercise lists {surface} as an employee on the training case."),
)

# (zone, REDACT frame, KEEP frame).  Every frame gives each identifier at
# least eight surrounding whitespace tokens, and the opposing texts make the
# same literal a person-bearing identifier or a technical configuration key.
STRUCTURAL_FRAMES = (
    ("code_identifier", "// synthetic reviewer assignment for practice\nconst reviewer = {surface};\nreturn reviewQueue.resolve(reviewer, policy);", "// synthetic policy setting for practice\nconst policyKey = {surface};\nreturn policyStore.resolve(policyKey, scope);"),
    ("code_identifier", "function routeSyntheticCase() {{\n  const assignee = {surface};\n  return trainingQueue.submit(assignee, reviewPlan);\n}}", "function routeSyntheticCase() {{\n  const setting = {surface};\n  return trainingQueue.submit(setting, reviewPlan);\n}}"),
    ("technical_id", "audit actor={surface} action=synthetic_review result=queued policy=training", "audit key={surface} action=synthetic_review result=queued policy=training"),
    ("json_value", "{{\"requested_for\":\"{surface}\",\"ticket_ref\":\"{ticket}\",\"workflow\":\"synthetic_review\",\"state\":\"queued\"}}", "{{\"configuration_key\":\"{surface}\",\"ticket_ref\":\"{ticket}\",\"workflow\":\"synthetic_review\",\"state\":\"queued\"}}"),
    ("code_identifier", "// demo approval context\nlet delegatedReviewer = {surface};\nlet outcome = evaluateSynthetic(delegatedReviewer, controls);\nreturn outcome;", "// demo configuration context\nlet delegatedSetting = {surface};\nlet outcome = evaluateSynthetic(delegatedSetting, controls);\nreturn outcome;"),
    ("technical_id", "event=demo_handoff requested_by={surface} queue=training state=waiting evidence=synthetic", "event=demo_handoff config_key={surface} queue=training state=waiting evidence=synthetic"),
    ("json_value", "{{\"approval_contact\":\"{surface}\",\"change\":\"{ticket}\",\"environment\":\"sandbox\",\"verified\":false}}", "{{\"rule_identifier\":\"{surface}\",\"change\":\"{ticket}\",\"environment\":\"sandbox\",\"verified\":false}}"),
    ("code_identifier", "class SyntheticReview {{\n  constructor() {{ this.owner = {surface}; }}\n  submit() {{ return this.owner + reviewContext; }}\n}}", "class SyntheticReview {{\n  constructor() {{ this.setting = {surface}; }}\n  submit() {{ return this.setting + reviewContext; }}\n}}"),
    ("technical_id", "log=practice_audit person={surface} operation=validate_mock_record result=pending", "log=practice_audit identifier={surface} operation=validate_mock_record result=pending"),
    ("json_value", "{{\"reviewer\":\"{surface}\",\"reference\":\"{ticket}\",\"source\":\"training\",\"retain\":false}}", "{{\"technical_token\":\"{surface}\",\"reference\":\"{ticket}\",\"source\":\"training\",\"retain\":false}}"),
    ("code_identifier", "// fictitious release gate\nconst humanOwner = {surface};\nconst message = buildPracticeNotice(humanOwner, releaseWindow);", "// fictitious release gate\nconst configOwner = {surface};\nconst message = buildPracticeNotice(configOwner, releaseWindow);"),
    ("technical_id", "service=sample_portal delegate={surface} event=mock_change status=scheduled trace=synthetic", "service=sample_portal option={surface} event=mock_change status=scheduled trace=synthetic"),
    ("json_value", "{{\"assigned_person\":\"{surface}\",\"case\":\"{ticket}\",\"phase\":\"rehearsal\",\"result\":\"open\"}}", "{{\"assigned_setting\":\"{surface}\",\"case\":\"{ticket}\",\"phase\":\"rehearsal\",\"result\":\"open\"}}"),
    ("code_identifier", "async function prepareDemo() {{\n  const contact = {surface};\n  return await syntheticReview(contact, evidenceBundle);\n}}", "async function prepareDemo() {{\n  const token = {surface};\n  return await syntheticReview(token, evidenceBundle);\n}}"),
    ("technical_id", "record=training_case reviewer={surface} action=fictional_approval outcome=recorded", "record=training_case key={surface} action=fictional_approval outcome=recorded"),
    ("json_value", "{{\"person_reference\":\"{surface}\",\"run\":\"{ticket}\",\"kind\":\"demo\",\"complete\":true}}", "{{\"config_reference\":\"{surface}\",\"run\":\"{ticket}\",\"kind\":\"demo\",\"complete\":true}}"),
    ("code_identifier", "// internal exercise only\nvar approver = {surface};\nvar state = processSyntheticApproval(approver, samplePolicy);", "// internal exercise only\nvar selector = {surface};\nvar state = processSyntheticApproval(selector, samplePolicy);"),
    ("technical_id", "audit=mock_workflow contact={surface} stage=review queue=simulation decision=waiting", "audit=mock_workflow config={surface} stage=review queue=simulation decision=waiting"),
    ("json_value", "{{\"delegate_name\":\"{surface}\",\"request\":\"{ticket}\",\"channel\":\"test\",\"notice\":\"synthetic\"}}", "{{\"delegate_key\":\"{surface}\",\"request\":\"{ticket}\",\"channel\":\"test\",\"notice\":\"synthetic\"}}"),
    ("code_identifier", "function auditPractice() {{\n  const namedReviewer = {surface};\n  return summarizeSynthetic(namedReviewer, auditTrail);\n}}", "function auditPractice() {{\n  const namedSetting = {surface};\n  return summarizeSynthetic(namedSetting, auditTrail);\n}}"),
)

STRUCTURAL_CONTEXTS = (
    ("Training review checks fictional routing before execution.", "Evidence remains inside the isolated demonstration boundary."),
    ("The rehearsal coordinator verifies this mock assignment carefully.", "No production identity is involved in this exercise."),
    ("A sandbox workflow records simulated approval context here.", "The practice case closes after synthetic verification."),
    ("This demo payload supports an invented service handoff.", "Reviewers use it only during the training session."),
    ("Sample controls document a non-production access decision today.", "The evidence bundle stays within the rehearsal scope."),
    ("The mock audit traces a fictional operational change.", "Its result is retained solely for the demo."),
    ("A training queue prepares the simulated review item.", "The test coordinator confirms the fabricated outcome later."),
    ("This internal exercise validates an invented workflow step.", "All surrounding details describe the sandbox environment."),
    ("The practice record captures a synthetic control checkpoint.", "No live account or customer data appears here."),
    ("A rehearsal plan routes the fictional request safely.", "The sample evidence is reviewed before closure."),
    ("Training operators inspect this mock release decision together.", "The scenario remains limited to non-production systems."),
    ("The demonstration log explains an invented handoff state.", "A later practice check records the simulated result."),
    ("This sample task models a fabricated approval path.", "The exercise team validates only synthetic evidence."),
    ("A sandbox case tracks the fictional review responsibility.", "Its mock status remains visible during the rehearsal."),
    ("The test workflow documents a simulated exception carefully.", "Training staff confirm the invented response afterward."),
    ("A practice register stores this artificial control event.", "The demonstration boundary prevents real-world use entirely."),
    ("This rehearsal message supports a fictional change review.", "The synthetic case is discarded after the dry run."),
    ("The internal demo follows an invented approval sequence.", "Only the training queue receives this sample artifact."),
    ("A mock service process records a fabricated routing choice.", "The exercise evidence remains separate from live systems."),
    ("This synthetic scenario tests a fictional reviewer flow.", "The practice audit notes the simulated completion state."),
)
